plt.figure(figsize = (10,10))
plt.title('Random Forest Classifier Confusion Matrix', fontsize = 20)
plt.ylabel('True Values', fontsize = 20)
plt.xlabel('Predicted Values', fontsize = 20)
cm_graph = yellowbrick.classifier.ConfusionMatrix(final_rf, classes = ['Not Arrested', 'Arrested'], fontsize = 20, cmap = 'BuPu')
cm_graph.fit(X_train_new, y_train)
cm_graph.score(X_train_new, y_train)
plt.show()

plt.figure(figsize = (10,10))
plt.title('SVM Classifier Confusion Matrix', fontsize = 20)
plt.ylabel('True Values', fontsize = 20)
plt.xlabel('Predicted Values', fontsize = 20)
cm_graph_2 = yellowbrick.classifier.ConfusionMatrix(final_svc, classes = ['Not Arrested', 'Arrested'], fontsize = 20, cmap = 'BuPu')
cm_graph_2.fit(X_train_new, y_train)
cm_graph_2.score(X_train_new, y_train)
plt.show()

plt.figure(figsize = (10,10))
plt.title('Gradient Boost Classifier Confusion Matrix', fontsize = 20)
plt.ylabel('True Values', fontsize = 20)
plt.xlabel('Predicted Values', fontsize = 20)
cm_graph_3 = yellowbrick.classifier.ConfusionMatrix(final_xgb, classes = ['Not Arrested', 'Arrested'], fontsize = 20, cmap = 'BuPu')
cm_graph_3.fit(X_train_new, y_train)
cm_graph_3.score(X_train_new, y_train)
plt.show()